#pragma once

// Some values to play with
#define MAX_INPUT_LENGTH 256
#define MAX_CHUNK_LENGTH 32
#define EPSILON 1e-10
#define ALLOWED_EQUATION_INPUT_CHARACTERS "1234567890-+=xX*^., "
#define ALLOWED_COEFFICIENT_INPUT_CHARACTERS "1234567890.-"

// Input types
enum INPUT_TYPE{COEFFICIENT_INPUT, EQUATION_INPUT};
#define INF 100

//#define DEBUG
